settings:
  # mysql
  database:
    # 数据库类型 mysql，sqlite3， postgres
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    dsn: root:root@tcp(127.0.0.1:3306)/knotice?charset=utf8mb4&parseTime=true&loc=Local
    # 空闲连接池中连接的最大数量
    maxIdleConns: 10
    # 打开数据库连接的最大数量
    maxOpenConns: 100
    # 连接可复用的最大时间(秒)
    connMaxLifetime: 3600
    #默认是否关闭事务 关闭可大约 30%+ 性能提升
    skipDefaultTransaction: true
